package com.dragon.miaosha.dataobject;

public class CommodityStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_stock.id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_stock.stock
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_stock.commodity_id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    private Integer commodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_stock.id
     *
     * @return the value of commodity_stock.id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_stock.id
     *
     * @param id the value for commodity_stock.id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_stock.stock
     *
     * @return the value of commodity_stock.stock
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_stock.stock
     *
     * @param stock the value for commodity_stock.stock
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_stock.commodity_id
     *
     * @return the value of commodity_stock.commodity_id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_stock.commodity_id
     *
     * @param commodityId the value for commodity_stock.commodity_id
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }
}