package com.dragon.miaosha.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_name
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    private String promoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_date
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    private Date startDate;
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.commodity_id
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_commodity_price
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    private Double promoCommodityPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.id
     *
     * @return the value of promo.id
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.id
     *
     * @param id the value for promo.id
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_name
     *
     * @return the value of promo.promo_name
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_name
     *
     * @param promoName the value for promo.promo_name
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.start_date
     *
     * @return the value of promo.start_date
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.start_date
     *
     * @param startDate the value for promo.start_date
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.commodity_id
     *
     * @return the value of promo.commodity_id
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.commodity_id
     *
     * @param commodityId the value for promo.commodity_id
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_commodity_price
     *
     * @return the value of promo.promo_commodity_price
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public Double getPromoCommodityPrice() {
        return promoCommodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_commodity_price
     *
     * @param promoCommodityPrice the value for promo.promo_commodity_price
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    public void setPromoCommodityPrice(Double promoCommodityPrice) {
        this.promoCommodityPrice = promoCommodityPrice;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}