package com.dragon.miaosha.dao;

import com.dragon.miaosha.dataobject.CommodityDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "CommodityDOMapper")
public interface CommodityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    int insert(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    int insertSelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    CommodityDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Dec 05 14:38:00 CST 2019
     */
    int updateByPrimaryKey(CommodityDO record);

    int increaseSales(@Param("commodityId") Integer commodity, @Param("amount") Integer amount);

    List<CommodityDO> listCommodity();
}