package com.dragon.miaosha.dao;

import com.dragon.miaosha.dataobject.PromoDO;
import org.springframework.stereotype.Component;

@Component("PromoDOMapper")
public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    PromoDO selectByPrimaryKey(Integer id);

    PromoDO selectByCommodityId(Integer commodityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Dec 17 10:52:45 CST 2019
     */
    int updateByPrimaryKey(PromoDO record);
}